apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: peloton-secret
spec:
  refreshInterval: '15s' # How often this secret is synchronized
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target: # Our target Kubernetes Secret
    name: peloton-secrets # If not present, then the secretKey field under data will be used
    creationPolicy: Owner # This will create the secret if it doesn't exist
  data:
    - secretKey: peloton_username
      remoteRef:
        key: peloton # This is the remote key in the secret provider (might change in meaning based on your provider)
        property: pelotonUsername # The property inside of the secret inside your secret provider
    - secretKey: peloton_password
      remoteRef:
        key: peloton
        property: pelotonPassword
    - secretKey: cloudflare_email
      remoteRef:
        key: cloudflare
        property: cloudflare_email
    - secretKey: cloudflare_api
      remoteRef:
        key: cloudflare
        property: cloudflare_api
